### ISSUE TITLE
Request: Sleeptimer

### ISSUE THREAD

**Issue by Hyperion923** [advplyr/audiobookshelf-app#10]

**Comment by advplyr** [comment]
Can you provide an example app using this functionality that you would like to see replicated?

**Comment by Hyperion923** [comment]
A good option would be like in the Audible a
![sleeptimer](https://user-images.githubusercontent.com/44998988/134809863-88a01930-9253-4503-bb1b-6492bef6c70c.jpeg)
pp

**Comment by Maximilian85** [comment]
2 two additions to the sleep timer. First, it's great when the sound gets quieter for about 20 seconds at the end of the timer and doesn't just go offMeaning a fadeout over 20-30 seconds before the end of the timer. And the timer can be reset by turning or shaking the phone. To be realised via the gyroscope sensor of the mobile phone. So the timer can be set to 10 minutes before sleeping and if you are not asleep yet or the book is too exciting, you can turn the mobile phone at the moment when the audio book is turned down by the fade out and the timer is set to 10 minutes again. This then works without the display having to be turned on. 

Keep an eye on the app "Smart AudioBook Player". This has the two functions described. 

Great work and many thanks for the project!

**Comment by advplyr** [comment]
Just released a basic sleep timer in `v0.9.14-beta`

I will leave this open because I'd like to implement @Maximilian85 suggestions still.

Let me know if this is working though.

**Comment by Maximilian85** [comment]
The sleep function works and is completely sufficient for the current status of the app. As you write, it would be great to refine the feature when there is time. 

Thanks a lot !

**Comment by advplyr** [comment]
Just released `v0.9.28-beta` which has some updates to the sleep timer.

The volume will start to fade out in the last 30 seconds of the sleep timer. Shaking the phone will add 15 minutes to the timer.

I wasn't sure the amount of time to add when shaking the phone, I just wanted to the get the volume and shaking added and we can smooth out the details.
I still haven't used the sleep timer on other apps, so please let me know any and all adjustments that make sense.

**Comment by FlamingoDaBird** [comment]
Hi
I tried out the new sleep timer:

if I let the timer run out when it hits the 30 seconds time frame limit to shake the phone...  The timer will hit 0 and then pause the stream as intended. 
But when I press play again the stream is muted, seems like the fade out is still ongoing in the last step, since the sound seems still to be very low or muted. I only tried a sleep timer of 1 minute to be able to run some tests quickly.
Another test gave me a different result, same as above but after 10-15 seconds the sound started playing as normal.

- After a few tests, the app seems to be set to fade out at 15 seconds left on the set timer and not 30 seconds anymore.

- If I let the timer run its course and I press play on my buds the timer will not be set again, it will be disabled.
would be nice to be able to regain the previously set timer if I accidentally miss that time frame.

Using the pause/play on my ear buds gives me another +15 minutes whenever I press play/pause.
I suppose its hard to set the addon of minutes to the 30 second fade out only? Or if it even makes sense? :) its all matter of opinions I guess. 
15 minutes or add the selected amount of minutes of the original sleeptimer? or just reset the timer? Tough choices. I like however an addon of +15 minutes, but adding everytime one pauses can be somewhat hard to keep track of, when I never look at my phone during nighttime.  And inserting every single possibility as a user option within the app can be overwhelming as well :) and result in more bugs, will be hard to track every feature that is user controllable ... 

Thanks for your quick updates and the progress of the application. Great work.

**Comment by advplyr** [comment]
> seems like the fade out is still ongoing in the last step, since the sound seems still to be very low or muted

Yeah this is exactly what is going on. I will fix this today.



> I suppose its hard to set the addon of minutes to the 30 second fade out only? Or if it even makes sense?

It's not hard, I just didn't think about it. Will also add this today. This should also resolve your last note about +15 minutes getting added everytime you play/pause.



> * If I let the timer run its course and I press play on my buds the timer will not be set again, it will be disabled.
>   would be nice to be able to regain the previously set timer if I accidentally miss that time frame.

I wasn't sure how this should function. I still haven't looked at other apps, so I'm relying on you all that use the sleep timer to let me know the best experience. If the sleep timer runs out and pauses the audio, then you press play again on your ear buds this should restart the sleep timer at the original time you selected? So if you selected a 60 minute sleep timer it will reset to 60 minutes? That just seems long to me, but I don't use it so maybe not.

**Comment by Maximilian85** [comment]
Hi 

thanks for the update!

I can confirm the observations of FlamingoDaBird. If the timer has expired and I press play again, it remains silent. I have to restart the app so that I hear something again. 

For me, the shaking did not work when the display is off. Shaking only works when the display is on. But then with each shaking +15 min. 

In my opinion, the previously set timer should be reset when shaking.
Here I think it would be useful to change the timer 1/5/10/15/30/45/60 min + and End of shapter. I used the timer rather for shorter times between 5 and 15 min. 

Is it possible to adjust the sensitivity of the gyro sensor? So that it is enough when the phone is turned once the timer is reset again? 

Thanks for your work.

**Comment by Maximilian85** [comment]
> I wasn't sure how this should function. I still haven't looked at other apps, so I'm relying on you all that use the sleep timer to let me know the best experience. If the sleep timer runs out and pauses the audio, then you press play again on your ear buds this should restart the sleep timer at the original time you selected? So if you selected a 60 minute sleep timer it will reset to 60 minutes? That just seems long to me, but I don't use it so maybe not.

I think it makes sense that as long as the timer is not turned off by me and I press play again, the last timer becomes active again. 

But that will be a user decision. 

Will there be later maybe an options menu where the user can set such options?

**Comment by advplyr** [comment]
@Maximilian85 Are you also referring to pressing play/pause on your headphones?

Right now I'm configuring this just for the headphone play/pause, the play/pause on the app will not reset the sleep timer.

**Comment by Maximilian85** [comment]
I did my test without a headset.

**Comment by advplyr** [comment]
@Maximilian85 Can you elaborate on what you mean by the phone is "turned" to extend the sleep timer?

**Comment by Maximilian85** [comment]
Right now I do have to shake the phone. I would love, if for example the phone is lying with the display to the ground that it would be enough to turn the display to the top, so just one turn. So what I mean on turning around would be from pointing up to pointing down of the display, or the outher way around. Shaking is getting me every time again awake.

**Comment by advplyr** [comment]
Updates in `v0.9.29-beta`

- The shake sensitivity decreased a lot
- The times changed to 1/5/10/15/30/45/60/90 and a +/- button to add or remove 5 minutes in the UI
- Fix the volume bug
- Shaking or play/pause on headset will only extend the timer if it is within 30 seconds of finishing OR if the sleep timer has finished within 2 minutes. If within 2 minutes of finishing a shake or play on the headset will both reset the sleep timer and play the audio.
- Sleep extend time is based on what you originally selected. So if you set a 5 minute sleep timer it will extend/reset to 5 minutes.

This is not yet live on the play store, but I wanted to write this out before I forgot. I will follow up when it goes live.
Thank you for helping to test and improve the app

**Comment by FlamingoDaBird** [comment]
omg your're quick. :)

Out of curiosity how long does it take for google store to deploy a new version? I bet its different in every other country as well.., 
I'm located in Sweden.

Thanks.

**Comment by advplyr** [comment]
I've had it take anywhere from 30 minutes to 5 days. One reason it can take longer is if you have the app enabled for android auto, then it has to go through the android auto testing & approval as well.

I realized I forgot about getting the shake feature to work when the screen is locked. So I just pushed `v0.9.30-beta` that will keep listening for shake events when the phone is locked. The sensor is unregistered 2 minutes after the sleep timer expires in order to save our precious phone battery.

**Comment by advplyr** [comment]
Those updates are finally available on the play store

**Comment by FlamingoDaBird** [comment]
I tried the v0.9.31-beta for a brief moment.... Seems like its working fine

shake function only enables when the 30 sec frame limit is in scope. Same for with buds play/pause
and the original set timer is added to the 1-30 seconds time frame 

Also the timer is kept if you miss 30 s time frame and you press play/pause on the buds!!

great work. Thanks @advplyr

**Comment by Maximilian85** [comment]
Perfect it works very well and I will still try it with different phone. 

Great work! Thanks
