### ISSUE TITLE
a few issues with the Android App

### ISSUE THREAD

**Issue by skyzuma** [advplyr/audiobookshelf-app#102]
Audiobookshelf Version: v1.6.69

#### Android Issue
- the library are in alphabetical order - no problem (not on web) and the first (on android (and web)) library will used everytime i open the app (web also) ... its possible to save the last spot? and the access is slow (local network (hosted on an pi 4 (see https://github.com/advplyr/audiobookshelf/discussions/377#discussioncomment-2221357)))

- the app / player is not fully closed, the player is always there ... i need to use the taskmanager (idk if this the right word) to close the app / player completly

- everytime i open the app > the player comes without any doing myself except open the app ... its possible to open the player first / only if i start the stream and close the player if the stream end?

- the app cant read the .epub books (same on web)

Android version: 9

Device model: Huawei P 10

Stock or customized system: Stock

**Comment by advplyr** [comment]
I believe the library order has been fixed for a while. 

It is intentional that you have to close the app completely to close the player.

The player no longer opens automatically.

Not sure about the epub. You can open a separate issue for that if it persists and please provide as much detail as possible.
