### ISSUE TITLE
Export progress and finished state to metadata.json

### ISSUE THREAD

**Issue by BeckenrandschwimmerTim** [advplyr/audiobookshelf-app#1029]
Hi there,
this is my first note/feature request in github at all, so please forgive me some mistakes.
I am a big fan of this software and guess it would benefit when the metadata.json could be filled with the progress and finished state.
Or is there another way to do that?

Thanks in advance!

**Comment by nichwall** [comment]
There is not currently a way to do that. The metadata JSON file is designed to be user agnostic (so nothing that is user specific). There is a feature request to export books as a CSV, so maybe this could fall under that (user and server specific exports).

In the meantime, you can access all of the data through the API if you wanted to access a script to automatically generate reports of some kind.
https://api.audiobookshelf.org

Also, I'm assuming you are meaning on the server, since this is the mobile app repo.

**Comment by BeckenrandschwimmerTim** [comment]
> There is not currently a way to do that. The metadata JSON file is designed to be user agnostic (so nothing that is user specific). There is a feature request to export books as a CSV, so maybe this could fall under that (user and server specific exports).
> 
> In the meantime, you can access all of the data through the API if you wanted to access a script to automatically generate reports of some kind. https://api.audiobookshelf.org
> 
> Also, I'm assuming you are meaning on the server, since this is the mobile app repo.

Thanks @nichwall for your reply.
Yes, this is helpful for me. I will follow the mentioned feature request.
And sorry for starting my request in the wrong section.
