### ISSUE TITLE
(iOS) App does not retain progress made while disconnected from server when it reconnects

### ISSUE THREAD

**Issue by XerxesDGreat** [advplyr/audiobookshelf-app#1175]
### Steps to reproduce
note: This requires the server to only be accessible at home and not publicly. For the following steps "home" means "connected to the wifi network which has the server", "away" means "not connected to the wifi network which has the server"

1. Download one of the books on the server to the device
2. While at home, start playing the title.
3. While the title is playing, leave home, disconnecting from home wifi
4. Continue playing for some time, then pause while away from home
5. Background the application
6. Arrive back home, foreground the application, then start playing the same title 

### Expected behaviour
- The title should resume playback at the time it was manually paused every time

### Actual behaviour
- The title intermittently resumes playback at around the time the device was last at home. There does not seem to be any specific action which makes this happen; sometimes it works as expected, but about 40% of the time, it does not.

### Environment data

Audiobookshelf Version: 0.9.73-beta

- [ ] Android App?
- [x] iOS App?

#### iOS Issue
iOS Version: 17.4.1

iPhone model: iPhone 15 Pro

**Comment by nichwall** [comment]
Does the behavior match this issue? There is a video in one of the comments.

https://github.com/advplyr/audiobookshelf-app/issues/1161

**Comment by noahkiss** [comment]
I'm still seeing an issue with time syncing as well. My audiobook will always reset to 0:00, and I never listen on the web, only on mobile. 

I use Tailscale to access my library from my iPhone, but I generally don't connect, I just listen to the local copy (I have the audiobook downloaded on my device).

Most recently when this happened, I did connect to Tailscale on my iPhone, but I don't remember even opening the ABS app. After disconnecting from TS, I opened the app and noticed that my progress had been reset to 0:00, and then I just now manually re-connected to sync to the server so I could see the logs.

Right now the only way I have to recover from this failure is to view the logs and do the math on last position + time listened before reset. 

**Since listening progress seems to be a pervasive bug, it would be great to have both a "Start Timestamp" and "End Timestamp" for each listening session, as well as to make the listening sessions available through the mobile interface, so that I can manually correct it if necessary without getting on a computer.**

<img width="872" alt="Listening Progress Resets" src="https://github.com/advplyr/audiobookshelf-app/assets/22437387/5802045c-6943-45b3-928d-352c8dd9daa7">

**Comment by nichwall** [comment]
> **Since listening progress seems to be a pervasive bug, it would be great to have both a "Start Timestamp" and "End Timestamp" for each listening session, as well as to make the listening sessions available through the mobile interface, so that I can manually correct it if necessary without getting on a computer.**

This functionality exists on Android, and there is an open feature request for the local history on iOS.
https://github.com/advplyr/audiobookshelf-app/issues/466

![Screenshot_20240416-080158.png](https://github.com/advplyr/audiobookshelf-app/assets/5686638/0b010722-7419-4fa5-bde9-8e0889fc8df4)

**Comment by noahkiss** [comment]
@advplyr Just to confirm, do you mean that fixing this bug is not planned? Or was that targeting the history page? Because this bug still exists.

**Comment by advplyr** [comment]
There was no response by the OP on whether this is the same as #1161 

Your issue doesn't seem to be the same as this one either. There was an issue opened recently about the book restarting at 0:00 but this turned out to be a bad audio file. https://github.com/advplyr/audiobookshelf/issues/2864

Syncing doesn't seem to be a pervasive bug so maybe you are coming across #1161 or a bad audio file?

**Comment by noahkiss** [comment]
Got it, thanks. I'll do some testing on my end to see if I can reproduce #1161. This issue sums up my experiences better, but I've never intentionally recreated it so there are assumptions on my part. Thanks for clarifying

**Comment by anakinsleftleg** [comment]
I don't think this issue should be closed. 

And it is not the same as #1161 which is described as going the other way (web to mobile). 

I experience this position reset all the time when i listen on mobile and then reconnect when i get home. it's super aggravating and i have to go into the history on the android app to go back to where i last stopped it. Maybe the underlying cause between this and the other issue are related/the same but this is a distinct interaction relative to the other mentioned issue. 

Not only that but many people seem to be having this issue, and of course you'll only hear from people who have the impetus to have or make a github account and desire to make the difficulty known. Most will think "oh it's just broken" and then abandon it.
