### ISSUE TITLE
[Enhancement]: If book already deleted remove from local library

### ISSUE THREAD

**Issue by MadBobUK** [advplyr/audiobookshelf-app#1227]
### Describe the Feature/Enhancement

If book already deleted remove from local library

### Why would this be helpful?

Books deleted by other app still show in local downloads, cannot re-download / cannot remove from list of local books 

### Future Implementation (Screenshot)

background function

### Audiobookshelf App Version

Android App - 0.9.74

**Comment by cassava** [comment]
I don't know if it needs to be a background task to clean out these, but it should at least be possible to manually "clean out" these entries.

**Comment by advplyr** [comment]
I just fixed an issue in v0.9.77 where it was impossible to delete items that were removed from the device on android. So you can remove these now but they aren't automatically removed.
Maybe they should show errors instead of being auto-removed so users don't think it just disappeared? Maybe there is a permission issue that needs to get resolved and that is the reason it isn't found.

**Comment by MadBobUK** [comment]
Happy that I can n manually delete the remnant of the book individually. No need to put extra effort into this. Really appreciated.
