### ISSUE TITLE
[Enhancement]: Android: Improve playback quality at playback rates >1x

### ISSUE THREAD

**Issue by mjiggidy** [advplyr/audiobookshelf-app#1370]
Playing back audio at higher speeds, for example 1.5x, introduces an annoying warble. Usually not all that bad when it's strictly speech, but very distracting when there is music or sound effects under the speech, like many podcasts do.

Certainly there will be some artifacting no matter what, but comparing the same podcast at 1.5x between Audiobookshelf and Spotify, for example, there is definitely room for improvement.

**Comment by advplyr** [comment]
I'm not aware of anything that could be done. We are using the built-in android audio player and passing in a playback rate like any other app would be doing as far as I know.
Comparing Spotify isn't a good example since it isn't using the same audio file. If you can try playing the audio file in another app that might be helpful.

When you open an issue please use the issue templates because it has you provide information that is helpful in debugging.

You can re-open the issue with the bug report template if you are able to notice a difference between Abs playing the audio file and another app playing the audio file that we can reproduce and hear the difference in.
