### ISSUE TITLE
Pause current track when disconnected from Bluetooth device

### ISSUE THREAD

**Issue by es9o** [advplyr/audiobookshelf-app#156]
I've noticed most media playing applications on Android pause when the phone is disconnected from a Bluetooth device. The assumption is that when someone disconnects their headphones, car stereo, etc., the media is no longer being listened to.

However, audiobookshelf continues playing and I recently lost my position in my book after not realizing this. I'm submitting this feature request to have it added in future builds.

Thanks!

**Comment by advplyr** [comment]
@alehel That would be great. We can handle iOS separately, it is far behind Android right now.

**Comment by alehel** [comment]
@es9o what version of Android and what headphones are you using? I just tested this on my Samsung S21 running Android 12 and I'm unable to reproduce with my Jabra Elite 65t headphones. I've tried,
- Putting headphones back in their case: abs pauses.
- Turning headphones off while they are connected using the power button on the headphones: abs pauses
- Turning bluetooth off on my phone: abs pauses.
- Putting the app in background and repeating the steps in the three points over: abs pauses
It seems to me like the OS is handling things as expected.

**Comment by advplyr** [comment]
Is this still an issue on the latest release? I'm not able to reproduce this.

**Comment by advplyr** [comment]
Is your situation the same as #612?

**Comment by advplyr** [comment]
I think this is specific to cars so I updated #612 and we can use that as the main thread if you want to follow there.

**Comment by Nintendork69** [comment]
Hey just noticed this has started happening on my Samsung note 9.

When disconnecting my jabra elite 65t (putting them into their charging case), the audio keeps playing out of my phone speaker, which if turned down I don't notice until much too late and lose my place in the book.

This also happens with my Sony Wf-1000xm4 ear buds when put back in their case.

Another part of the issue is that if the sleep timer is active, and I turn off my wh-1000xm4 over ear headphones, it pauses, however if I move my phone it starts playing again as if sleep timer is awake. Will keep tabs on the issue as it seems intermittent at times.
