### ISSUE TITLE
Buffer/cache to prevent redownloading content on auto-rewind.

### ISSUE THREAD

**Issue by DDriggs00** [advplyr/audiobookshelf-app#203]
### Is your feature request related to a problem? Please describe.
When resuming after more than a couple seconds, the player skips back a few seconds. When this happens, it takes some time to resume, presumably to re-download the part to be replayed. 

### Describe the solution you'd like
Keep a cache/buffer going back the maximum length of auto-rewind, so there will not be a requirement to re-download any content on resuming playback.

**Comment by DieselTech** [comment]
To add on to that: In my opinion if a book is 'on deck' it should stay transcoded and ready to until it's marked as finished. 

I'm seeing the long wait times without even skipping around. Just starting up a session again after not playing it for a while makes it wait. It looks like FFmpeg is only using a single thread during all of this, so on a multi-hour book it will take time to finish.

**Comment by advplyr** [comment]
In the majority of cases the item is not getting transcoded anymore, it is getting direct played on your device.

Unless you are using Flac, Opus, Ogg it is direct playing the audio file. I'm not sure how to handle buffering or caching a direct play since all of that is handled natively via the browser or via the audio player on your mobile device.
I'm sure there is something we can do here but I haven't dug into it yet.

**Comment by advplyr** [comment]
There is an open issue for keeping the transcode which if implemented might solve your issue https://github.com/advplyr/audiobookshelf/issues/768

That being said direct play should be working for the majority of cases. There was a bug with firefox and direct play m4b but that should be fixed now also.
