### ISSUE TITLE
Bad new version

### ISSUE THREAD

**Issue by orrionis** [advplyr/audiobookshelf-app#27]
Hy
I m so sorry but your latest version on playstore, 9.16
Dont Work on m'y Phone. Samsung a52 Android 11.
Before all fine. But now it s crach continualy. 

I hope your resolve in few time 

Good luck , hope it goes well !

Tanks for your work

**Comment by advplyr** [comment]
I don't see any crash logs. When is it crashing? As soon as you open the app?

If you have an audiobook currently playing, close it in the web app, then open the mobile app again.

**Comment by proteus077** [comment]
Not that it has been an issue for me but just thought I'd let you know, when I updated to the latest version today the app did crash once on me, however it's been fine since. For reference I'm running a Samsung Galaxy S21 (Exynos) on Android 11. Happy to dig up logs or provide any information that might help.

**Comment by advplyr** [comment]
I haven't heard any more reports on this, so it looks like just a one-off thing. Please re-open if you have any other info.
