### ISSUE TITLE
Android Auto - On load displays only downloads section

### ISSUE THREAD

**Issue by andonevris** [advplyr/audiobookshelf-app#310]
### Steps to reproduce

1. Start Android Auto without AB running on phone
2. Android auto only displays download section.
3. Starting AB on phone and pressing play causes pink dot to appear
4. clicking on pink dot AB loads correctly from then on
5.

### Expected behaviour
- Tell us what should happen
- On first connect all sections should be available

### Actual behaviour
- Tell us what happens
- Only downloads section available on Android Auto, need to manually start stream from phone for proper functionality

### Environment data

Audiobookshelf Version:
2.1.1
- [x ] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 10

Device model: Samsung Galaxy S10

Stock or customized system: Stock, rooted

**Comment by advplyr** [comment]
I'm not sure what you mean by a pink dot appears.
The download section only shows if a connection to the server was able to be made.

**Comment by andonevris** [comment]
When this issue arises there is no way to navigate anywhere or start playing a podcast from android auto as you are stuck in the downloads section with nothing else available.

When you start playing something from the phone a pink circle in android auto appears on the right of the screen, when you tap that it opens the currently playing podcast and everything is fine, all sections appear and you can navigate as normal.

**Comment by tehniemer** [comment]
I am having this same issue. It's stuck showing downloads with no way to navigate to anything else.

**Comment by raphpa** [comment]
I do see the same behavior. It might happen when the app is not able to connect back to the server.

**Comment by advplyr** [comment]
When the app is launched from Android auto it will attempt to connect to a server. Starting from the first server config and looping through until one succeeds. You will only see a download section if all the connection attempts fail.

I haven't been able to reproduce this since the connection succeeds for me. We could try putting something in that attempts to connect multiple times but as far as I know Android auto doesn't have a way to convey information about the failed attempt.

A few things you can try that will give us more info:

1. Before connecting to Android auto open the app on your phone and connect to the server. Once you are connected to your server in the app then hookup to Android auto.
2. If you have both an external connection config and an internal connection config in the mobile app then make sure your external connection config is the first one listed. For example, you may have `https://abs.yourserver.com` and `http://192.168.1.1:13378` in your list of connections. If you have the internal one listed first you can remove it, then re-add it so it shows second. This would ensure the first connection attempt will be the external one that is accessible outside your home network.

**Comment by raphpa** [comment]
I am using a VPN connection to connect back to my NAS at home. It happens if that connection is not working at the moment the app tries to connect.

I have not read much yet into the android auto api, but I don't see that behaviour on other apps like Symfonium. 
As far as I can see onGetRoot() gets only called once and then never again. Would it be possible to use a fixed or cached root? 

Google has an example where they detach from the onLoadChildren() call in case of a network error and notfify a callback once results are ready. Not sure if this is applicable here though.
[https://github.com/android/uamp/blob/main/common/src/main/java/com/example/android/uamp/media/MusicService.kt](https://github.com/android/uamp/blob/main/common/src/main/java/com/example/android/uamp/media/MusicService.kt)

**Comment by advplyr** [comment]
Yeah onGetRoot gets called once on launch, then each time you change menus. We are already detaching and using the callback for that reason. We detach, attempt to connect to a server, then return the results.

**Comment by juli-dot-md** [comment]
I'm still experiencing this issue with the latest versions of the server and app. When I open the app, wait until it's ready and then connect the car, everything works fine. Otherwise I only get the downloads screen. Opening the app on the phone while connected does not fix it, playing content from the app does.

I tried a tasker script that launches the app when connected but that's not fast enough.

**Comment by juli-dot-md** [comment]
[abs_logs_android_0.12.0-beta.txt](https://github.com/user-attachments/files/26281301/abs_logs_android_0.12.0-beta.txt)

The logs from today. Lots of connection errors. When I use the app on the phone, there are no issues at all.
