### ISSUE TITLE
A 'temp bookmark' function which will be removed when returned to

### ISSUE THREAD

**Issue by HStep20** [advplyr/audiobookshelf-app#311]
### Is your feature request related to a problem? Please describe.
As I listen to something before bed, I put on a sleep timer. Most nights I fall asleep about 10-15 minutes in, and it just finishes in 20. Id love to have some sort of quick UX function to set a temporary bookmark so when I wake up I can go back to my place and skip forward a bit to try and find the last thing I remember. 

### Describe the solution you'd like
I figure the ux could be something like
- Quick Bookmark/Temp Bookmark button located to the left of the play speed button creates a 'temp bookmark' and is turned to an active state
- When Quick Bookmark/Temp Bookmark button is pressed again, it is changed to an inactive state, and returns the player to the location of the temp bookmark, while deleting the temp bookmark.

It would not be a real persistent bookmark with all the ui navigation of a bookmark, but a quick, one button option to create a single temp bookrmark

**Comment by advplyr** [comment]
You would like to press this "temp bookmark" button before you start the sleep timer so you can jump back to that position the next morning?
Not sure I understand the use-case yet.

**Comment by HStep20** [comment]
Yep. Its kind of just a fluff feature that would smooth out the UX for people who fall asleep listening to them and want to quickly return to where they were the night before. It just saves the extra user steps of making a bookmark and deleting a bookmark every single day by turning it into its own function that auto deletes.

Totally get it if it isn't worth implementing.

**Comment by advplyr** [comment]
This is more complicated then you might think because that temp bookmark would still need to be persisted as the phone goes to sleep. I would also be hesitant to add this to the UI because it would add clutter for most people that would never use it and also probably require an explanation somewhere.
When bookmarks get fully implemented perhaps there is a solution that can be built into that to make it easier. Something to think about further down the road.
