### ISSUE TITLE
Play/pause remote button on Android TV not working as expected

### ISSUE THREAD

**Issue by galaxyfar** [advplyr/audiobookshelf-app#358]
### Steps to reproduce

1. v0.9.57-beta on Nvidia Shield (also happening on generic Android TV box, so not a Shield issue per se)
2. Play any audiobook, press play/pause remote button
3. Play will either not pause (if already playing) or with resume (if already pause)

### Expected behaviour
- Play/pause remote button should play/pause playback (this was not an issue with older version, sorry I lost track, which was last stable release)

### Actual behaviour
- Play/pause remote button it acting wonky with only this app. Other music app responds to play/pause as expected

### Environment data

Audiobookshelf Version:

- [ v0.9.57-beta] Android App  

#### Android Issue
Android version: 11 

Device model: Nvidia shield TV Pro

Stock or customized system: No

**Comment by dalins** [comment]
### Steps to reproduce

Same as original post.

**Additional information:**
When a Bluetooth headset is used and the app is in the foreground, it works. But when the app is in the background, it does not work. I also tried a wired headset and with that it doesn't work in the foreground or background.

### Expected behaviour

Same as original post.

### Actual behaviour

Same as original post.

### Audiobookshelf Version:

[ v0.9.57-beta] Android App

### Android Issue

Android version: 11

Device model: Hallo Welt Systeme / Volla Phone

Stock or customized system: Stock system (Android without Google Services)

**Comment by advplyr** [comment]
This should be fixed in the next release. Along with #427 #429

**Comment by advplyr** [comment]
Fixed in [v0.9.62-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.62-beta)
