### ISSUE TITLE
BUG: App Loses position of audiobook randomly

### ISSUE THREAD

**Issue by feerlessleadr** [advplyr/audiobookshelf-app#41]
Hi - Opening a separate issue from my feature request to keep things simpler. I'm using 0.9.27-beta of the android app, and for the most part everything works great. I have noticed on a few occasions however that I will be listening to a book (m4b format, streaming), and I'll stop the book, do something else on my phone for a while, and then when I come back to the app, my listening position has jumped backward approx 5 minutes. 

I can't quite figure out what is triggering this to make this repeatable, but not sure if others have seen this behavior.

**Comment by FlamingoDaBird** [comment]
Hi 

- just adding my random thoughts to this issue as a normal user of the app :)

I haven't seen this issue yet. 
I know some audiobook apps tends to rewind up to 2 minutes depending on how long ago it was since you listened. Was wondering if the application has that kind of feature that results in some kind of bug? Not sure how it saves progression either? If it needs to save a file on the phone, syncs to the server? Dependent on being able to keep itself alive on the phone for a while? Background service, recent android versions kills application running in the background, if not told different in the OS-settings for that particular app.

**Comment by feerlessleadr** [comment]
Just to update - I've encountered this bug a few more times - seemingly at random. It usually jumps back between 5 and 10 minutes.

**Comment by feerlessleadr** [comment]
I've noticed this happening a few times today, and I think I've narrowed down the issue to the app temporarily losing connectivity to the server at the same time that the book is paused. 

Whenever I get into the car, I plug my phone into Android Auto and listen to a book through the app. Wen I pull back into my driveway, I will pause the book when I stop the car and get out to go inside. During that same time, my phone is usually switching from cellular data to wifi, and the app will temporarily lose connection to the server. 

I notice that about half the time, when I start up the book later, instead of starting from the point that I stopped when I got out of the car, the book will play from about the same position as when I originally started the book when I got into the car. Almost as if the app didn't save the position, and instead of sending the updated position of the book to the server, the book position on the app is overwritten by the last played position of the server.

**Comment by advplyr** [comment]
Ohh that is what you mean, yeah the android auto isn't setup to update progress yet.
I'm going to try to get that working this weekend, but there is a lot to be done with android auto I only got the very basic implementation started. I haven't yet figured out how this will support multiple libraries, right now it is only using the main library, so that will be tricky.

**Comment by feerlessleadr** [comment]
Thanks - don't get me wrong, 50% of the time I use Android Auto, it updates the position on the server, and 50% of the time it doesn't. I would also say like 10% of the time I use the app with regular Bluetooth (with my headphones or something, no AA), the same thing happens. 

I do have some other bugs/requests [here ](https://github.com/advplyr/audiobookshelf-app/issues/2#issuecomment-989187180), so if you'd rather, happy to opened up separate issues for each item. 

Overall though, especially considering the 'newness' of this project, it is really great and works really well. Thanks!

**Comment by tvories** [comment]
> Ohh that is what you mean, yeah the android auto isn't setup to update progress yet. I'm going to try to get that working this weekend, but there is a lot to be done with android auto I only got the very basic implementation started. I haven't yet figured out how this will support multiple libraries, right now it is only using the main library, so that will be tricky.

Do you ever live stream your coding?  AA is something I've wanted to get more into and it would be cool to discover it along with you.  Does the project have a discord server?

**Comment by advplyr** [comment]
Nope, I don't stream.
AA has not been a great experience so far.. because the docs and examples are limited. I haven't been able to get the voice commands working and found no info on how to get your app name recognized, "Play X in audiobookshelf". I want to set the chapter forward/backward buttons to jump forward/backward, like in the google podcast app, but found no docs on that either. Publishing updates to the play store takes about 5 days instead of a few hours when not enabling AA.

No discord server. The project is still young with a small community, so the github threads have been enough to house the discussion. I hope to encourage more developers to contribute, especially with the app.

**Comment by tvories** [comment]
@advplyr thanks for the info, and I have to say, awesome work on this project so far.  Discord is nice for collab, but I'm sure github threads work for now as well. These are all fun problems, and I hope I have some time to contribute!  At the very least to the docs :D
