### ISSUE TITLE
Play/pause not working on *some* bluetooth headphones

### ISSUE THREAD

**Issue by catuan** [advplyr/audiobookshelf-app#429]
### Description

When listening to audiobooks with my Bose NC 700 wireless headphones, activating play/pause from headphones has no effect (audiobook keeps on playing). When using Airpods Pro (gen 1), play/pause works as expected. Audiobooshelf is the only android app I'm experiencing this problem with. All other apps I've tested (Spotify, Youtube, etc...) works fine, and I can play/pause what I'm listening to from the Bose NC 700 headphones.

### Steps to reproduce

1. Connect headphones to phone with bluetooth (Bose NC 700)
2. Start listening to audiobook
3. Activate play/pause on headphones

### Expected behaviour
- Playback should pause

### Actual behaviour
- Playback continues

### Environment data

Audiobookshelf Version: 0.9.57-beta (server: 2.2.1)

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 13

Device model: Pixel 4a

Stock or customized system: Stock

**Comment by DDriggs00** [comment]
Same issue with Sony WF1000-XM4

**Comment by advplyr** [comment]
@DDriggs00 Are you also on Android 13?

**Comment by DDriggs00** [comment]
> @DDriggs00 Are you also on Android 13?

I'm using Android 11, Stock OxygenOS on Oneplus 7T

**Comment by tehniemer** [comment]
Same issue with wireless Android Auto using  AAWireless device.

**Comment by galaxyfar** [comment]
Like to report my finding if it helps to resolve the issue:

1. Issue is not bluetooth headphone centric per se, Play/Pause refuse to work even with bluetooth keyboard and well as Logitech RF keyboard. 

2. When Play/Pause button is press once, app briefly pauses the playback but resume playing right away. If Pause button is pressed longer and then released, it may or may not eventually pause. It appears to be the app is not registering keystroke correctly due to some delay related glitch (recall Nvidia Shield had this bug where single press on Volume Up would ramp the volume all the way up, rattling the whole home, was only fixed rather recently in firmware)

3. I reported same [issue ](https://github.com/advplyr/audiobookshelf-app/issues/358)back in Sept and can confirm older releases  (all else being equal, Android OS version to be precise) worked perfectly fine. So bug must around that timeframe and carried forward since then.

**Comment by AudiobookConnoisseur** [comment]
I am on the iOS version, and I am having this same issue with a pair of replica AirPods pro. Interestingly, the in-ear-detection works every time. If I take the headphone out, the app pauses, and it resumes when I put the headphone back in. The play and pause squeeze button on the AirPods rarely works. If the audio has been paused for more than 30 seconds or so, play will work sometimes, but the squeeze button never works for pause. 

For reference, I never have issues with play/pause on these headphones on any other app.

**Comment by advplyr** [comment]
I found the issue for this on Android.

**Comment by advplyr** [comment]
Fixed in [v0.9.62-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.62-beta)
