### ISSUE TITLE
[Android Auto] launcher doesn't show audiobookshelf as an option

### ISSUE THREAD

**Issue by kidwellj** [advplyr/audiobookshelf-app#432]
I'm working with a Fairphone 4 running Android 11. Having installed the app via apk, I have since removed it and reinstalled via play (aurora) store and am running 0.9.59. Regardless of configuration, when I open Android Auto settings panel and "customise launcher" the app simply isn't listed as an option. Others, such as Waze, are...

**Comment by GittenKittens** [comment]
I'm encountering this exact same issue with the app not listed as available in Android Auto.  I installed the latest apk via this Github's release page.

Phone: Pixel 6
Android version: 13
App version: 0.9.59

**Comment by kidwellj** [comment]
Fix found: I had disabled several google services (in an attempt to partially de-google by fairphone4), once re-enabled apps all popped up on Android Auto including audiobookshelf. Hope that helps others!

**Comment by ggrensteiner** [comment]
Even tho this is closed, I've had the same issue. I run this software from the resease download and not from Google Play, which may be related.

I had to enable developer settings and turn on unknown sources, I don't know if this is an android 13 or samsung specific issue/fix.

Just posting for anyone searching for this issue and the workaround, the ticket doesn't need to be reopened.

**Comment by advplyr** [comment]
This has to do from not getting it from the Google Play store

**Comment by knw257** [comment]
In case anyone finds this thread encountering the same problem, the workaround suggested by @ggrensteiner above still works, with a slight modification. Since Android Auto is now in the phone settings on most newer devices, you have to find it there. The rest is still correct - tap the Android Auto version item 10 times until it says Developer Mode is enabled, then hit the three dots in the upper right corner and select Developer Settings, then scroll down and make sure Unknown Sources is checked. To verify, go back to the main app settings and open "Customize Launcher", and AudioBookshelf should now appear in that list. Hopefully someone else finds this useful.
