### ISSUE TITLE
Downloaded file is not shown or disappears from App

### ISSUE THREAD

**Issue by TheSylus** [advplyr/audiobookshelf-app#436]
### Steps to reproduce

1. Download any audiobook
2.
3.

### Expected behaviour
- The file(s) should be downloaded
- The audiobook should be seen as local
- One can play the audiobook

### Actual behaviour
- Files get downloaded. 
- Somestimes the book is shown as local, but not always. Sometimes the local book disappears after a day or two.
- The audibook can be played, when it is still shown as local. (Streaming always works)

I think the downloading is fine, as the files / or one file are actually downloaded and can be played by another player. 
Going to local files and scan of force rescan does not help
The files or metadatet isnot edited or changed

### Environment data

Audiobookshelf Version: 

v2.2.3 (but also older version)

- [x ] Android App?
- [ ] iOS App?

#### Android Issue
Android version:
 0.9.59 but also older

Device model:

Several android phones in the family: Samsung, Huawei

Stock or customized system:
All Stock roms

#### iOS Issue
iOS Version:

iPhone model:

**Comment by advplyr** [comment]
Sounds like an issue with permissions. When the app starts up it is going to check if your downloaded audiobooks still exist. If the app doesn't have permission to access the folders/files anymore then it will remove them.

I'm not sure how to fix these permission issues and haven't had them myself on several devices. You can try storing your audiobooks in a folder on the device that is created by default. Instead of creating a new folder on your device most android phones comes with pre-made folders.
