### ISSUE TITLE
Android app fails with basic-secure-headers middleware enabled in traefik

### ISSUE THREAD

**Issue by nova-ace** [advplyr/audiobookshelf-app#437]
### Steps to reproduce

1. Audiobookshelf server running with traefik ingress and basic-secure-headers middleware
2. Cannot connect with app. Fails with "Unknown Error"

### Expected behaviour
- Should be able to connect with secure header injection

### Actual behaviour
- Cannot connect with app. Browser connections work fine.

### Environment data
Audiobookshelf running on Truenas Scale with Truecharts images of both Audiobookshelf and Traefik. There is limited user configurability to remove middlewares on this system. A workaround has been viable until Truecharts Audiobookshelf version 2.2.1_3.0.0 by disabling basic-secure-headers Traefik middleware. This workaround is no longer supported. This is a very basic security setting that the app should likely support.

Audiobookshelf Version:  Multiple up to 2.2.1

- [X ] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 12 and 12L

Device model: Motorola Edge 2021 and Samsung Galaxy Tab S8

Stock or customized system: Stock

Untested on iOS app

**Comment by advplyr** [comment]
> There is limited user configurability to remove middlewares on this system

I'm not sure what you mean. What configurability is available?


> A workaround has been viable until Truecharts Audiobookshelf version 2.2.1_3.0.0 by disabling basic-secure-headers Traefik middleware. This workaround is no longer supported.

Nothing has been changed about how requests are handled in audiobookshelf. It seems like you may be confusing some package that Truecharts is offering with audiobookshelf.

> This is a very basic security setting that the app should likely support.

I'm not sure that the app doesn't support this since I don't know what this setting is. The app is just making regular HTTP requests to the server, nothing special is happening with headers. What needs to be updated to support this setting?
