### ISSUE TITLE
BUG: Rightside hamburger menu not on top

### ISSUE THREAD

**Issue by FlamingoDaBird** [advplyr/audiobookshelf-app#45]
Hi

I noticed that the right side hamburger menu isnt on top  when you jump from tab to tab  (series and library) see pic below
where all the heavy loading takes place to display all the books.
My library is quite huge as well, so it could be that? 

Jumping between tabs takes a while as well, the app becomes a little unresponsive.
I'm not sure I'm using the Libraries correct?

I'm pointing the main folder in my unraid docker to
\media\
then I created two libaries pointing to:
\media\audiobooks\
\media\ebooks\

Is the main Media library that always present be the one containing all the libraries? 
If I create several subfolders in my \meda\ folder will the server application read from those as well? If I intend to say have \media\music\  and other stuff in there´that might slow down the application?

Thanks.

![image](https://user-images.githubusercontent.com/47981216/143719070-2a377e8e-72d9-4461-9115-49cf3a7e12b7.png)

**EDIT
even if the picture states that I'm downloading an audiobook, it is sluggish even without downloading as well :)

**Comment by advplyr** [comment]
That is strange.. I can't reproduce this issue. Any suggestions on how I can reproduce that?

The app is not yet optimized at all for large libraries. It is still loading and displaying the entire library at once.
The web app only just started getting optimized by only displaying the books in view, it is still slow though because it is pulling in the entire library.

**Comment by FlamingoDaBird** [comment]
Its probably the optimization thing then. Even if I select my audiobook library : 694 items i still get that bug, but that is still a lot of audiobooks to shift through I'm guessing.

Funny thing is, i click on Library, wait a few moments (10 -20 sec) and press the menu it is not entirely visible as shown in the pic above.
But if I scroll all the way down to the bottom of the list the menu pops out and becomes entirely visible. It is stuck during the entire scroll process as shown in the picture above. While being at the bottom of the list I can pop up the menu and close it at will.
Then if I scroll back up again to the top, I can repeat the issue.

**Comment by FlamingoDaBird** [comment]
I tried two other phones:
Oneplus Nord CE 5G
Samsung S8+

Got the same weird result on both of  them.

**Comment by advplyr** [comment]
I just realized what is happening. The shelves have a decreasing z-index starting from the total number of shelves, this is so the shadow of the shelf above doesn't get covered by the shelf below. Since you have over 50 shelves, the top N - 50 shelves will be a larger z-index then the drawer.

This is an easy fix I'll include in the next release. Google play store keeps rejecting every other release stating that they need test credentials to access the in-app content. I reached out explaining the app has no content and it is the users own content, but to no avail.
I put in some obnoxious messages, so hopefully the sleep timer updates get approved.
![image](https://user-images.githubusercontent.com/67830747/143723636-eed7897f-cc36-40c7-83ee-4af15c5a8fc7.png)

**Comment by FlamingoDaBird** [comment]
Hi,
Is this fixed in v0.9.31-beta?
I tried it out and its still the same issue.

**Comment by advplyr** [comment]
Not yet, I will be re-doing the mobile app bookshelf to work with large libraries like I just did with the web app.

**Comment by advplyr** [comment]
Forgot about this, was fixed a while ago.
