### ISSUE TITLE
Hide download notification 

### ISSUE THREAD

**Issue by lukeIam** [advplyr/audiobookshelf-app#495]
### Is your feature request related to a problem? Please describe.
When I download a single audiobook with >150 parts to my android device a get a lot of annoying notification.
Even better: my android system groups them in groups of 20 -> I have so slide them away more then seven times.

### Describe the solution you'd like
No (system) notifications for downloading all the single files.
I have the progress in app (would be enough for me) but some single notification from audiobookshelf showing the progress (xx from yy) would be nice.

### Additional context
Disabling the "system downloader notification" should be easy. I just had a short look into your code - should be this line:
https://github.com/advplyr/audiobookshelf-app/blob/master/android/app/src/main/java/com/audiobookshelf/app/plugins/AbsDownloader.kt#L98
changed to `DownloadManager.Request.VISIBILITY_HIDDEN`
If there is already an options the disable the download notifications then I'm sorry (pretty new to audiobookshelf and currently testing if it can replace my current audiobook app)

**Comment by advplyr** [comment]
`VISBILITY_HIDDEN` requires extra permission. I changed to `VISIBILITY_VISIBLE` and this works well because the notification is there while downloading but disappears after completion. When it shows during download these will be collapsed together.

Source: https://developer.android.com/reference/android/app/DownloadManager.Request#setNotificationVisibility(int)

**Comment by advplyr** [comment]
Updated in [v0.9.61-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.61-beta)
