### ISSUE TITLE
iOS ebook download

### ISSUE THREAD

**Issue by Jmanko16** [advplyr/audiobookshelf-app#496]
### Is your feature request related to a problem? Please describe.

- the app on iOS has no way to download an epub or pdf ebook.  While there is a built in reader it does not format well on devices, and there is no way to open in another app (for example Apple Books).

### Describe the solution you'd like

- add download button for ebook.  Allow selecting epub or pdf if both versions exist.

**Comment by advplyr** [comment]
As a temporary workaround for this, the website client is built to work on mobile so you can use that to download files. The website can also be installed as a PWA.

**Comment by jtbrush56** [comment]
When doing this as a PWA on iOS, there is no indication that a download is being done until it is complete. Additionally, the default download button does more than just download the epub file. It downloads all files in a zip format. It might be more user friendly to have a separate button that “downloads all ebook files” for a particular book. That last point might just be my own use case though since you can get just the ebook by going to the individual files at the bottom.

**Comment by advplyr** [comment]
Added in [v0.9.65-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.65-beta)
