### ISSUE TITLE
[Bug] App always starts with "bookshelf empty" message

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf-app#53]
Everytime I start the app, it shows the following screen.
![Screenshot_20211203-105718_AudioBookshelf](https://user-images.githubusercontent.com/42061703/144550671-89ff9f13-1784-4a1d-b9cc-b3b6aa297e99.png)

It's only after a few seconds (about 7-10s) that my books load into the app.

**Comment by advplyr** [comment]
This is likely because you have a large collection and the mobile app is still loading and mounting every book right away. The mobile app bookshelf is about to get rewritten.

**Comment by raviwarrier** [comment]
Oh that good news, because right now it is really slow. For example, I started a book last night (and as promised) thought I'd give the app a try. But when I clicked search, it took about 5-7 seconds for the search feature to pop up. 
Will wait for the re-write to start testing the app.

**Comment by advplyr** [comment]
I just released `v0.9.32-beta` and is pending approval on the play store right now. While implementing the new faster bookshelf I found and fixed many bugs. I'll follow up here when it is available on the play store.

**Comment by MidnightSnowleopard** [comment]
After update to the latest version I'm now experiencing the same lack of books.  Unlike the original though I don't see any ever populate.

I do have a large library and before the update my phone struggled extremely heavily with the application but it did load them.  Searching for books pulls up results as normal and they can be entered into that way and they can play and sync playing live from a browser.

May be related or not but this is a slightly older phone and no image covers have ever loaded correctly on it.  They all say "Invalid Cover".  This does not occur on a different newer phone that this was tested on.

**Comment by advplyr** [comment]
`v0.9.32-beta` is live in the play store. I had to push another patch because libraries were not getting loaded when connecting to the server for the first time.
Please let me know if the performance has improved, a 1000 book library and a 50 book library should have the same performance on first launch.

@MidnightSnowleopard Are you connecting to your server with SSL? Are you connecting via reverse proxy? Are the covers downloaded?

**Comment by MidnightSnowleopard** [comment]
Connecting to the server via reverse proxy with SSL.  Cert is valid and fully online and accessible with normal operation through web browser.

Updated now again to v0.9.33-beta with no change.  Server logs show connection successfully with two pings before connection.

`[2021-12-07T21:28:03.717Z]  INFO: Recieved ping
[2021-12-07T21:28:03.822Z]  INFO: Recieved ping
[2021-12-07T21:28:04.453Z]  INFO: [SOCKET] Socket Connected UbWcJ1jf8DOsAQnJAAAP`

Only difference from server logs between when connecting with web browser vs. app is the two pings.  Web browser still works correctly.  Searching for a book still pulls up correct results that browsable and playable.  Still just the different tabs that are not pulling up anything with Library, Series, and Collections all reporting 0

**Comment by advplyr** [comment]
If you use the mobile browser to access the web app, are you able to load everything okay?
Do you have your books in the main library?

**Comment by MidnightSnowleopard** [comment]
Using mobile browser brings it up correctly without issue including covers rendering correctly and not showing as invalid.

There are 1400 registered books in the main library with that currently being the only library.

**Comment by advplyr** [comment]
This is sounding like an issue with the SSL certificate. Is this a self-signed certificate?
A similar issue was #28

**Comment by MidnightSnowleopard** [comment]
Nope, fully valid and signed SSL cert.  No warnings when attempting to browse either from internally or externally the certs are fully valid.

**Comment by advplyr** [comment]
Have you tried without SSL?

**Comment by MidnightSnowleopard** [comment]
Just tested, exact same behavior without SSL.  Everything works correctly including mobile browser except for the app itself.  Still the exact same behavior without the slightest change from removing SSL.

**Comment by advplyr** [comment]
And without the proxy?

**Comment by MidnightSnowleopard** [comment]
Exact same behavior even with connecting directly from phone to direct IP address.

**Comment by MidnightSnowleopard** [comment]
Will add that this was working, slowly, before the updated app.  Have tried removing all data and reinstalling the new app with no change in behavior.

**Comment by MidnightSnowleopard** [comment]
Found the issue, something with my version of server was incorrect.  Started fresh with the latest release 1.6.39 and it loads again.

**Comment by raviwarrier** [comment]
@advplyr will test out the new version from playstore in a day or two.

**Comment by Budlyte** [comment]
Mine still loads with this "Bookshelf Empty" message on launch.   **Version 0.9.40-beta**  This isn't the real issue for me though.

The app frequently crashes when loading my library, on launch. BUT! if I can manage to open the menu and go to "Account" before the app crashes, then the library loads in the background. I can watch it load on the thin black progress bar up top. Once that's done then I can go into any tab and the app works fine.   Except for my Downloads folder, that one keeps crashing.

Figured I would mention all that here since it seems possibly related to library size, and this issue.

**Comment by advplyr** [comment]
Are you switching between servers or users in the app? Or are you always using the same?

Have you downloaded any audiobooks? Do you have one of the devices that was crashing when pressing play on downloaded audiobooks?

I don't think yours is a library size issue, the fix for that was just only requesting part of the library at a time. So the initial load of a 1000 book library and a 10 book library should be roughly the same.

**Comment by Budlyte** [comment]
Not switching servers, though I am connected over the internet. That way I never have to switch.
Always the same user.  All I'm doing is opening the app, but it crashes when loading the library while on the library.

I have downloaded 2 audiobooks, though I deleted one of them from X-plore. Maybe that's causing an issue?

Maybe you are on to something about it having to do with something that crashed in the player. I uninstalled the app and reinstalled and it's fine again for now.  Going to download another book and poke at it again.

Any way to get logs from the app?
