### ISSUE TITLE
Can't play next episode without closing player

### ISSUE THREAD

**Issue by hobesman** [advplyr/audiobookshelf-app#601]
### Steps to reproduce

1. Play a podcast episode to the end
2. Try to press the "Next episode" button
3.

### Expected behaviour
- Tell us what should happen
Be able to play the next episode by pressing the button once the previous episode finishes.

### Actual behaviour
- Tell us what happens
Button doesn't work because an episode of that podcast is in the player. But the episode is finished. I have to open the player, manually close it, then I can press the play next button.
### Environment data

Audiobookshelf Version: 2.2.15

- [ ] Android App?
- [ ] iOS App?

#### Android Issue
Android version:

Device model:

Stock or customized system:

#### iOS Issue
iOS Version:

iPhone model:

**Comment by advplyr** [comment]
I'm confused on how to reproduce this one. I go to a podcast page and play an episode until it ends leaving the audio player open. As long as the audio player is open then the play button will stay "Playing". It is only until I close the audio player that I see "Next Episode".

As far as the current user experience this is not great and needs to be improved, but just talking about the bug here I'm not sure how to reproduce it.

**Comment by advplyr** [comment]
In testing I was using a downloaded episodes which is why the button says "Playing". When streaming the button will say "Streaming".

I also just caught a bug where the downloaded episode progress isn't being updated.
