### ISSUE TITLE
[Android] Downloading on Android 10 and below (SecurityException: Permission Denial)

### ISSUE THREAD

**Issue by Demian98** [advplyr/audiobookshelf-app#635]
### Actual behaviour
- I'm downloading all audiobooks I'm listening on the phone. This works well, but after a phone reboot the app just crashes on opening, without doing anything. When starting the app, it loads the main screen and crashed after around 2 seconds. I can start it again and again, it is an infinite loop.
- Other people in my family are experiencing the same issue.
- The only solution is to reinstall the app. Login again and redownload the audiobooks.
- The exception is: SecurityException: Permission Denial: reading.
- In the app settings all permissions are still granted, nothing was removed.

### Steps to reproduce

1. Install the app and login.
2. Download some books and listen to them.
3. Reboot the phone and open the app.

### Expected behaviour
- It should not crash and still keep the permissions after reboot of the phone.

### Environment data

Audiobookshelf Version:

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 10
Device model: SM-N975F

Stock or customized system: Stock

### Screenshots
![226367494-6dadc3e8-9d6e-4080-9d55-fc4ded63f5d6](https://user-images.githubusercontent.com/77210091/231402070-18ae8381-356c-44a0-a216-6596af009007.jpg)
![226367538-1149ee46-57fe-4a1d-9c0f-4c3364a78344](https://user-images.githubusercontent.com/77210091/231402088-68de8782-065c-47e5-ac50-34b6117d1413.jpg)
![226367547-133c7deb-3796-4c4b-88f0-1288f669d989](https://user-images.githubusercontent.com/77210091/231402090-2bd86206-bdd9-4bc3-9bd2-402fd05ed4d9.jpg)

**Comment by advplyr** [comment]
I'm not sure, I haven't seen that before. This is the same issue as #608 and is specific to Android 10. Maybe also Android 8 & 9 but I haven't gotten any reports for that.

**Comment by Demian98** [comment]
OK, something that needs to be fixed. Is there any way how I can help you with this?

To the general approach of offline files on ABS: Why is the user required to choose a specific directory for offline files? Most other app (Spotify, Netflix, and a lot more) are saving offline content into the app data, where the user has no access to.

Here are some benefits of the app data approach:
- Easier to understand/use for most end-users, special for the non-technical people.
- Most likely easier to handle for the developer, as there should be less security issues (like this one).
- Much better for privacy, as the offline files can currently be accessed by all apps with storage permission.
- This would fix the issue to link a book which was downloaded by another installation of the app (#653 #157), as it can't happen any more.

But the most important benefit for me would be easier handling for non-technical users. Like the most in my family :)

@advplyr It would be great to get your opinion on that :)

**Comment by advplyr** [comment]
We may be able to have a setting for storing in App data.

I took that approach because then it allows the user to manage the files on their device themselves. Some users also download the audio files and use a different app to listen. This was particularly useful in earlier development when the Abs mobile app was still missing a lot of features. I think many users prefer the files be stored where it is accessible to them so if we got rid of it entirely there would be a lot of requests to bring it back I'm sure.

I also had the thought that if we are building the mobile app with all these features for audiobooks then why not also allow it to be a standalone app. This ended up adding more work then I thought (like linking that you mentioned) so I may get rid of this concept.

I think these other media services you mentioned use App data because the content can be DRM protected so they don't want you having access to the files.

Anyway, I think we can try a hybrid approach of allowing users to store library items in app data or shared storage. I'm not sure what the UI/UX would look like for this. Maybe defaulting to app data but adding a prompt for if they want to use shared storage. Since these permission issues happen at Android 10 and below we could force those devices to use app data.

**Comment by Demian98** [comment]
I'm with you, removing the ability for users to store data in their own paths would cause a lot of complaints, as they are already used to this feature.

I like the idea of a hybrid approach, as it bring the simplicity which is missing currently and all the advanced users are still abele to use the advanced features.

Furthermore, I think I have a good idea for the UI/UX and the concept of how it could work:
This is the current menu for "Local Media". There could be a folder called "App Data" by default, which cannot get deleted.
![SmartSelect_20230414-124714_audiobookshelf](https://user-images.githubusercontent.com/77210091/232026038-6e40647f-c834-4e43-9a1c-0389f1ae9932.jpg)

This would then be available in this usual list to select from, when you download something.
![SmartSelect_20230414-124833_audiobookshelf](https://user-images.githubusercontent.com/77210091/232026537-b8c76c34-f81d-420c-b4f8-ddd4c005c6ef.jpg)

All the users which don't care, can just leaf it like it is and stay with the default folder "App Data". Brings the benefit that they are abele to start downloading after app setup. All the advanced users can still use the existing setup to do own configuration.

Additionally, you also don't need to care about backwards compatibility, as the existing thing stay like they are :)

**Comment by advplyr** [comment]
Yep, I like that

**Comment by Demian98** [comment]
Great, I can't wait to use the new feature 👍

**Comment by Demian98** [comment]
Hi @advplyr, I hope you are doing well. Is there already a rough time line, when this will be implemented?

**Comment by advplyr** [comment]
Hey, I don't have a timeline for this

**Comment by advplyr** [comment]
I've got this working and tested on a Pixel phone Android 9 & 10. By default all android versions will default to internal storage unless you go into Local Media and add a folder.
For Android 10 and below there will be a message saying downloads will go to internal storage but there is an option to override incase someone on Android 10 does have permissions working.

The "Internal App Storage" folders won't be there until something is downloaded there.

![image](https://github.com/advplyr/audiobookshelf-app/assets/67830747/ebcc2c9e-c552-4222-a529-cc0b1580a6bd)

In this case I didn't have any podcast folders setup yet so it defaults to Internal App Storage.

![image](https://github.com/advplyr/audiobookshelf-app/assets/67830747/1ce73e52-cf40-47ba-9fe6-388b6b36738f)

**Comment by Demian98** [comment]
Hi @advplyr, sounds like it is working well. Thanks a lot for the solution, it will bring much benefit to the audiobookshelf. I can't await to use it on my own :)

**Comment by peveleigh** [comment]
Came here looking for a fix to this problem and it looks like I just need to wait for the next release. My app crashes trying to access local files after a reboot on Android 9.

**Comment by advplyr** [comment]
Yep I should get a release out this week/weekend sometime.

**Comment by advplyr** [comment]
Added in [v0.9.65-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.65-beta)

**Comment by KellicTiger** [comment]
This issue is not resolved. The problem just occured with me on Samsung Fold 4 with Android 14.  I've been going alone without issue for months and then Monday the app started crashing on trying to play a downloaded book.  Reinstalled the app twice...no luck. Used the process above, made a new folder and gave permissions. Then pointed download to that folder and downloaded again....works. as best I can tell there is no  inherent ability to grant permissions to the app for local storage. 
Well I am not a programmer I feel like it's possible this app is using a permissions methodology that may have been depreciated by Google and/or Samsung. I know that I've run across permission problems with storage on other apps that are older as well.
Maybe this? https://stackoverflow.com/questions/72948052/android-13-read-external-storage-permission-still-usable
