### ISSUE TITLE
offline behaviors (filter and prefer local files first)

### ISSUE THREAD

**Issue by vbatts** [advplyr/audiobookshelf-app#668]
### Is your feature request related to a problem? Please describe.

Preparing for a trip I downloaded several books, and while I still had mobile reception it appeared my listening was still steaming direct, rather than using the local copy.

Then when looking for the books I had downloaded, there was no way to distinguish or filter on books that had downloaded a local copy.

### Describe the solution you'd like

Ideally there would be a toggle to be in offline mode.
This mode would automatically limit the books,series, etc to only things that are downloaded local.

This same filter could be usable while online to view and manage downloaded content.

### Describe alternatives you've considered

.. putting the whole device in airplane mode while listening to a book.
It is less than ideal.

**Comment by jurgenhaas** [comment]
I second that proposal. Struggling with exactly the same thing. Just wanted to also mention, that under such circumstances, where you're on the road with limited bandwith, going to the home screen always loads data from the server, where caching that content locally would bring a huge performance boost.

**Comment by Dr-Blank** [comment]
When you download the book while listening, it would continue to stream until you close the player and play again, or start another book and play the previous book again.

Also when offline, my continue listening shows up with offline books just fine.

Android

**Comment by jurgenhaas** [comment]
> Also when offline, my continue listening shows up with offline books just fine.

Yes, but the request above is about not being offline and seeing sub-optimal performance.

**Comment by advplyr** [comment]
There are "Local Books" and "Local Podcasts" shelves on the home page.
We could add a filter in the library tab to filter for books/podcasts available offline.

As for offline mode I think simply logging out of the server is the same thing, right? If you log out of the server you will only see downloaded media.

Caching is separate from this request which is for viewing media available offline.

**Comment by jurgenhaas** [comment]
> There are "Local Books" and "Local Podcasts" shelves on the home page.

Yes, but I have to open one of those local podcasts to see, how many unlistened episodes were available. The number on the shelf is the overall number of local episodes, not the number of unlistened episodes. And when I can't find what I'm looking for, I have to go back to the shelf and go into the next one. However, going through the shelf can be a problem when you're remote and not offline (see below).

> We could add a filter in the library tab to filter for books/podcasts available offline.

That would be helpful.

> As for offline mode I think simply logging out of the server is the same thing, right?

No, because when logging back in, you need your credentials again. Turning on offline mode would just be the app operating like being logged out, but turning in off, the app will be connected without me having to login again.

> Caching is separate from this request which is for viewing media available offline.

Only mentioned it here because going to the shelf to see the local podcasts over and over again can be extremely slow because the app always reads the full content from the server.

**Comment by advplyr** [comment]
> No, because when logging back in, you need your credentials again. Turning on offline mode would just be the app operating like being logged out, but turning in off, the app will be connected without me having to login again.

Your credentials don't need to be entered again

**Comment by jurgenhaas** [comment]
Hmm, that sounds like a misconception then. And could be perceived as a security issue by some.

Logout and going oggline should be 2 different things.
