### ISSUE TITLE
BUG/Enhancement: I can't seem to track forward or backward by sliding the playback progress bar

### ISSUE THREAD

**Issue by Kudjo-Grand** [advplyr/audiobookshelf-app#7]
I'm not sure if this is a bug (because it's SUPPOSED to work like this and currently doesn't) or an enhancement request (because it is NOT possible at this time, but I think it would be good to have in there.)
 
At this time, it seems the ONLY way to advance or "rewind" on the book I'm playing back, are to use the skip forward and skip backward buttons or the chapter select section.

Do you think this would be useful to add/fix?

What are your thoughts?

P.S. This is becoming so useful and polished, that I'm certain it will handle MANY people's use case, perfectly. Keep it up. I still have a handful of ideas, but I just wanted to take a moment to tell you that this is GREAT! Thank you for creating it.

**Comment by advplyr** [comment]
Thank you for all your help. The track only support clicking (tapping) to change the current time, which isn't very useful with audiobooks because they are typically 10+ hours.
I haven't come up with a good solution for this yet. How can we allow seeking to a specific time or just allowing for more precision when seeking?

**Comment by proteus077** [comment]
Hey @advplyr my suggestion though I'm not sure how difficult this would be, would be to have the progress bar track the current chapter rather than the full book, just so there is a bit more accuracy for seeking. The other thing that could be implemented is a scaling seek bar, for example the way that Youtube does it on long videos. If you visit [this video](https://www.youtube.com/watch?v=RDfjXj5EGqI) for example and drag the seek bar upwards, it then allows you to seek using the full screen width in a ~10 minute period. Hopefully I've explained that well.

**Comment by FlamingoDaBird** [comment]
I also mentioned something similar in #46 
Could that be something you're also interested in as a feature request?
Thanks.

**Comment by advplyr** [comment]
See updates in #46, changing the main track to use the chapter is now supported.
