### ISSUE TITLE
Scale chapter times with playback speed

### ISSUE THREAD

**Issue by advplyr** [advplyr/audiobookshelf-app#726]
Same as was implemented on web https://github.com/advplyr/audiobookshelf/issues/1647

**Comment by advplyr** [comment]
Updated in [v0.9.65-beta](https://github.com/advplyr/audiobookshelf-app/releases/tag/v0.9.65-beta)

**Comment by dedors** [comment]
This is still a issue with the history.

BUT, I would really like an option to disable the re-calculation of played & total time everywhere. I'm fine with re-calculated remaining time.
Because when I change the playback speed mid book, it gets really confusing where I am.
Btw, this is the way SABP is handling playback speed time calculations, so I'm probalby not the only one that likes it/is used to that way
