### ISSUE TITLE
Android notification playback speed incorrect

### ISSUE THREAD

**Issue by nichwall** [advplyr/audiobookshelf-app#764]
### Steps to reproduce

1. Set playback speed to a value that is not a preset (using the +/- of 0.1 increments)

### Expected behaviour
- Notification for playback should show the playback value

![App view](https://github.com/advplyr/audiobookshelf-app/assets/5686638/c1a382d5-a988-4c4f-ad63-606ecba1411d)

### Actual behaviour
- Playback speed in notification is the last playback speed which matches a preset (either by using a preset or using +/- 0.1 to reach a preset)

Screenshot should be 1.7 to match previous screenshot

![Notification](https://github.com/advplyr/audiobookshelf-app/assets/5686638/b3403ddd-8165-415b-92a6-64f866c68188)

### Environment data

Audiobookshelf Version: 0.9.65-beta

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 13

Device model: Pixel 6a

Stock or customized system: Stock

**Comment by advplyr** [comment]
I'm not sure we will support this yet since the playback speed shown on the notification is actually an icon and not text. So to support every value there we would have to include dozens of icons.

We currently use 6 icons. 0.5x, 1x, 1.2x, 1.5x, 2x, 3x.

I thought it would be better to have the playback speed adjustable there and round to the nearest icon then to not include the playback speed there at all.
We could put in some more icons to fill the gaps between 1x and 2x but I imagine we would still get bug reports so it may be better to remove the feature.

**Comment by nichwall** [comment]
Oh that's nifty. I didn't notice you could tap there and change the playback speed since I almost never change it. This is not a problem for me, I just wanted to document it somewhere for when someone else notices it.

I think the current selection of presets is good enough for changing between playback speed from the notification.

**Comment by advplyr** [comment]
We'll keep the current functionality for now. Maybe in the future android will allow us to put a custom value there instead of using icons.
