### ISSUE TITLE
[Android App] No cast button

### ISSUE THREAD

**Issue by shlomitan** [advplyr/audiobookshelf-app#817]
### Steps to reproduce

1. Go into android player
2. Play a book (or don't, doesn't matter) 
3. No cast button anywhere

### Expected behaviour
- Cast button to show up so I can select device to cast. When I went to the web player the button was there.
- Checked on my wife's phone, the button is there! 

### Actual behaviour
- I can't find the button :(

### Environment data

Audiobookshelf Version: server 2.2.23, app 0.9.65

- [*] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 12

Device model: Samsung s10e

Stock or customized system: stock

#### iOS Issue
iOS Version:

iPhone model:

**Comment by advplyr** [comment]
Maybe this is something with the network your device is connected to? Abs is using the google cast library that is detecting castable devices. If one is found then the button is shown. This seems like something with your device and not a bug within Abs so try experimenting with settings.

Have you installed the app from the google play store?

**Comment by shlomitan** [comment]
I have no idea why, but restarting after reporting here fixed. Didn't help before.
Thanks, and I hope to never complain again!
(BTW - I love abs. You're amazing for making this happen)

**Comment by LoudSoftware** [comment]
Am currently running into this issue, the only way to resolve this is to close the app and force stop it from settings and restart it.

Perhaps it might be better if the cast button always be present (or at least an option to do so in the settings)?

Otherwise, if the current behaviour is intended, an option to force refresh/scan for cast devices (maybe pull down in library to refresh?) could work as well.

In any case, I have a feeling the app doesn't always scan or remember previous scan results (even though the network didn't change)
