### ISSUE TITLE
Change play order of podcasts

### ISSUE THREAD

**Issue by timosturm** [advplyr/audiobookshelf-app#835]
### Is your feature request related to a problem? Please describe.
As far as I can tell, there are two types of podcasts:
1. with independent episodes
2. with ordered episodes (e.g., https://thehistoryofrome.typepad.com/revolutions_podcast/)

The default (and as far as I can tell fixed) behavior of audiobookself (web + app) is to play podcasts based on the release date. For the first type this is no problem, but for the second type it does not make sense to begin with the last episode of a podcast. Rather I would like to start at the beginning. The problem here is, that even sorting the episodes by episode does not change what is played when I click "Play" in the web view and in the (android) app. This is also true for "Play next Episode".

### Describe the solution you'd like
I would be happy if I could change the behavior to instead play by the order of episode.

### Describe alternatives you've considered
Alternatively, I add my podcast as audiobooks instead. This will retain the episodic structure. Also this allows auto-play of the whole podcast instead of having to manually select each episode to play.

**Comment by jaknz** [comment]
I've just installed audiobookshelf today and I'm loving it! Except that most of the podcasts I follow are serial, and need to be played oldest first. I wanted to put my voice behind this feature request (rather than creating another issue!) as well. It does seem like the simplest option would be to display and play serial-tagged podcasts in oldest-first order, and episodic-tagged podcasts newest first. Podcasts already have this tag, so you wouldn't need to store anything extra in the DB — just change the app's behaviour based on the tag when it's displaying or queuing for playback.
