### ISSUE TITLE
Android app has fully stopping playing any books

### ISSUE THREAD

**Issue by ameyp** [advplyr/audiobookshelf-app#836]
### Steps to reproduce

1. Launch app, select a book and click on Stream
2. Nothing happens
3. Select a book and click on Download, confirm, click on Play
4. Get error saying "Playback Failed: Source error"

### Expected behaviour
- I should be able to stream and play downloaded books

### Actual behaviour
- Neither work. This started manifesting with me being unable to stream or play new books. So I uninstalled and reinstalled the app, and now I can't even play audiobooks that were in progress in the app. I can play them just fine using Chrome on the same phone.

### Environment data

Audiobookshelf Version: v2.2.4

- [x] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 0.9.65-beta

Device model: Samsung Galaxy S22

Stock or customized system: Stock

#### iOS Issue
iOS Version:

iPhone model:

**Comment by nichwall** [comment]
Android app version 0.9.65 requires at least server version 2.2.23

You need to update your server. If you are upgrading to the latest version (2.3.3 as of writing this), you should first upgrade to 2.2.23 and ensure everything is still working correctly before upgrading to 2.3.3 due to a database migration for 2.3.x

**Comment by ameyp** [comment]
Thank you, that worked, I didn't realize I was that much out of date. Do you have a feature request to surface a warning in the app if the server version is too old?
