### ISSUE TITLE
iOS App Leaving Beta?

### ISSUE THREAD

**Issue by ohare93** [advplyr/audiobookshelf-app#897]
I see the iOS app is still in beta, any idea when it will be out for all to get?

Context: Don't get me wrong, I have no issues with the app being considered beta. My only issue is the availability, the TestFlight hasn't been accepting more testers. I already have the app, and have been enjoying it for a long time *but I cannot get the app for a family member*. I wish to share my audiobook library with them, and can only do so with the web app. App > web app for me, as it's much simpler to let audiobook.mydomain.com/api calls through my reverse proxy's security middleware (traefik with authelia) than it is to teach my parent to do two factor sign-in 😅

**Comment by nichwall** [comment]
There is not currently an estimated time that the apps will leave beta (there isn't a real roadmap beyond "planned features in no specific order" due to being a passion project).

My personal opinion as someone who doesn't actually do any of the development is at least 6-12 months, but could be longer depending on how long various parts of the server and app development take.

A few thousand testflight spots were opened a week or two ago when users who didn't update were removed, so there should still be some room. There are also a few third party apps people have written, but no idea on if they're still maintained or how well they work.
